### ISSUE TITLE
Implement `From<Owned>` for `Cow<'_, Borrowed>`

### ISSUE THREAD

**Issue by Emilgardis** [neoeinstein/aliri_braid#6]
Similar to https://doc.rust-lang.org/std/string/struct.String.html#impl-From%3CString%3E-4
This would allow 

```rust
#[aliri_braid::braid]
pub struct Foo;

struct Bar<'a> {
    foo: Cow<'a, FooRef>,
}

fn main() {
    let foo_owned: Foo = Foo::from("Hello!");
    let bar = Bar { foo: foo.into() }
}
```

**Comment by neoeinstein** [comment]
Included this in the recent change set, and included this code as a test for the three braid types. Thanks for the issue! Now released as 0.1.7.
