### ISSUE TITLE
no way to put proc-attributes on borrowed type

### ISSUE THREAD

**Issue by Emilgardis** [neoeinstein/aliri_braid#9]
```rust
// run cargo doc with `RUSTDOCFLAGS="--cfg nightly"`
#![feature(doc_cfg)]
use aliri_braid::braid;

#[braid]
#[cfg(any(docs, feature = "thing"))]
#[cfg_attr(nightly, doc(cfg(feature = "thing")))]
struct Thing;
```

above example will put a cfg and doc_cfg on `Thing`, but not on `ThingRef`.
This results in some wierd state for documentation, for example, docs will be (from real example)
![image](https://user-images.githubusercontent.com/1502855/131215350-715e3a3f-3512-4dbb-a4cc-2bc8092e1b31.png)

I'd want to be able to put a `#[doc(cfg(...))]` on the `Ref` as well.

**Comment by Emilgardis** [comment]
Note that I can solve this by putting each braid in a mod gated with `#[doc(cfg(...))]` (because `doc_cfg` propagates to all members/items) and `pub use` its items, but that feels sub-optimal.

**Comment by neoeinstein** [comment]
Would allowing something like `#[ref_attr(…)]` be a viable way of resolving this? I may be able to have the proc macro look for attributes like that, unwrap them, and then associate them with the reference type.

**Comment by Emilgardis** [comment]
I think the approach with always applying to both makes the most sense to me, but there's probably some pitfall there with assumptions on derives. 

I do like `ref_attr`, perhaps as `#[braid(ref_attr(...))]`.
